# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predictMatY <- function(x, E, D, b) {
    .Call('_FraseR_predictMatY', PACKAGE = 'FraseR', x, E, D, b)
}

predictMatC <- function(x, E, D, b, sf) {
    .Call('_FraseR_predictMatC', PACKAGE = 'FraseR', x, E, D, b, sf)
}

truncNLL_db <- function(par, H, k, n, rho) {
    .Call('_FraseR_truncNLL_db', PACKAGE = 'FraseR', par, H, k, n, rho)
}

truncGrad_db <- function(par, H, k, n, rho) {
    .Call('_FraseR_truncGrad_db', PACKAGE = 'FraseR', par, H, k, n, rho)
}

