# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predictYCpp <- function(H, D, b) {
    .Call('_FraseR_predictYCpp', PACKAGE = 'FraseR', H, D, b)
}

predictMuCpp <- function(y) {
    .Call('_FraseR_predictMuCpp', PACKAGE = 'FraseR', y)
}

estLgammaAlpha <- function(y, pos, ar) {
    .Call('_FraseR_estLgammaAlpha', PACKAGE = 'FraseR', y, pos, ar)
}

estLgammaBeta <- function(y, pos, br) {
    .Call('_FraseR_estLgammaBeta', PACKAGE = 'FraseR', y, pos, br)
}

truncNLL_db <- function(par, H, k, n, rho, lambda) {
    .Call('_FraseR_truncNLL_db', PACKAGE = 'FraseR', par, H, k, n, rho, lambda)
}

truncGrad_db <- function(par, H, k, n, rho, lambda) {
    .Call('_FraseR_truncGrad_db', PACKAGE = 'FraseR', par, H, k, n, rho, lambda)
}

truncNLL_e <- function(par, x, D, b, k, n, rho) {
    .Call('_FraseR_truncNLL_e', PACKAGE = 'FraseR', par, x, D, b, k, n, rho)
}

truncGrad_e <- function(par, x, D, b, k, n, rho) {
    .Call('_FraseR_truncGrad_e', PACKAGE = 'FraseR', par, x, D, b, k, n, rho)
}

truncNLL_rho <- function(rho, yi, ki, ni) {
    .Call('_FraseR_truncNLL_rho', PACKAGE = 'FraseR', rho, yi, ki, ni)
}

fullNLL <- function(y, rho, k, n, D, lambda, byRows = FALSE) {
    .Call('_FraseR_fullNLL', PACKAGE = 'FraseR', y, rho, k, n, D, lambda, byRows)
}

truncWeightedNLL_db <- function(par, H, k, n, rho, lambda, w) {
    .Call('_FraseR_truncWeightedNLL_db', PACKAGE = 'FraseR', par, H, k, n, rho, lambda, w)
}

truncWeightedGrad_db <- function(par, H, k, n, rho, lambda, w) {
    .Call('_FraseR_truncWeightedGrad_db', PACKAGE = 'FraseR', par, H, k, n, rho, lambda, w)
}

