# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

truncNLL_db <- function(par, H, k, n, rho, lambda) {
    .Call('_FraseR_truncNLL_db', PACKAGE = 'FraseR', par, H, k, n, rho, lambda)
}

truncGrad_db <- function(par, H, k, n, rho, lambda) {
    .Call('_FraseR_truncGrad_db', PACKAGE = 'FraseR', par, H, k, n, rho, lambda)
}

truncNLL_e <- function(par, x, D, b, k, n, rho) {
    .Call('_FraseR_truncNLL_e', PACKAGE = 'FraseR', par, x, D, b, k, n, rho)
}

truncGrad_e <- function(par, x, D, b, k, n, rho) {
    .Call('_FraseR_truncGrad_e', PACKAGE = 'FraseR', par, x, D, b, k, n, rho)
}

predictMuCpp <- function(H, D, b) {
    .Call('_FraseR_predictMuCpp', PACKAGE = 'FraseR', H, D, b)
}

truncNLL_rho <- function(rho, mui, ki, ni) {
    .Call('_FraseR_truncNLL_rho', PACKAGE = 'FraseR', rho, mui, ki, ni)
}

fullNLL <- function(mu, rho, k, n, D, lambda) {
    .Call('_FraseR_fullNLL', PACKAGE = 'FraseR', mu, rho, k, n, D, lambda)
}

